#!/usr/bin/env python3
"""Define constants."""

# pylint:disable=no-member
# constants exist in constants.py

# name to use for a group when no group tag is included in load_spec
DEFAULT_DATABASE_GROUP = "NO GROUP"

# Maxiumum number of columns
MAX_COL = 120

# line types
FHO = "FHO"
CTC = "CTC"
CTS = "CTS"
MCTC = "MCTC"
MCTS = "MCTS"
CNT = "CNT"
SL1L2 = "SL1L2"
SAL1L2 = "SAL1L2"
VL1L2 = "VL1L2"
VAL1L2 = "VAL1L2"
PCT = "PCT"
PSTD = "PSTD"
PJC = "PJC"
PRC = "PRC"
ECLV = "ECLV"
MPR = "MPR"
NBRCTC = "NBRCTC"
NBRCTS = "NBRCTS"
NBRCNT = "NBRCNT"
ISC = "ISC"
RHIST = "RHIST"
PHIST = "PHIST"
ORANK = "ORANK"
SSVAR = "SSVAR"
GRAD = "GRAD"
VCNT = "VCNT"
RELP = "RELP"
ECNT = "ECNT"
ENSCNT = "ENSCNT"
PERC = "PERC"

LINE_TYPES = [FHO, CTC, CTS, MCTC, MCTS, CNT, SL1L2, SAL1L2, VL1L2, VAL1L2,
              PCT, PSTD, PJC, PRC, ECLV, MPR, NBRCTC, NBRCTS, NBRCNT, ISC,
              RHIST, PHIST, ORANK, SSVAR, GRAD, VCNT, RELP, ECNT, ENSCNT, PERC]

LC_LINE_TYPES = [ltype.lower() for ltype in LINE_TYPES]

ALPHA_LINE_TYPES = [CTS, CNT, PSTD, NBRCTS, NBRCNT, MCTS, SSVAR, VCNT]

COV_THRESH_LINE_TYPES = [NBRCTC, NBRCTS, PCT, PSTD, PJC, PRC]

# Lower Case true and false
LCTRUE = "true"
LCFALSE = "false"

# Not Available - NA
NOTAV = "NA"

# column names
VERSION = "VERSION"
MODEL = "MODEL"
DESC = "DESC"
FCST_LEAD = "FCST_LEAD"
FCST_VALID_BEG = "FCST_VALID_BEG"
FCST_VALID_END = "FCST_VALID_END"
OBS_LEAD = "OBS_LEAD"
OBS_VALID_BEG = "OBS_VALID_BEG"
OBS_VALID_END = "OBS_VALID_END"
FCST_VAR = "FCST_VAR"
FCST_UNITS = "FCST_UNITS"
FCST_LEV = "FCST_LEV"
OBS_VAR = "OBS_VAR"
OBS_UNITS = "OBS_UNITS"
OBS_LEV = "OBS_LEV"
OBTYPE = "OBTYPE"
VX_MASK = "VX_MASK"
INTERP_MTHD = "INTERP_MTHD"
INTERP_PNTS = "INTERP_PNTS"
FCST_THRESH = "FCST_THRESH"
OBS_THRESH = "OBS_THRESH"
COV_THRESH = "COV_THRESH"
ALPHA = "ALPHA"
LINE_TYPE = "LINE_TYPE"
FCST_INIT_BEG = "FCST_INIT_BEG"

FCST_LEAD_HR = "FCST_LEAD_HR"

# After units added in MET 8.1
LONG_HEADER = [VERSION, MODEL, DESC, FCST_LEAD, FCST_VALID_BEG, FCST_VALID_END,
               OBS_LEAD, OBS_VALID_BEG, OBS_VALID_END, FCST_VAR, FCST_UNITS, FCST_LEV,
               OBS_VAR, OBS_UNITS, OBS_LEV, OBTYPE, VX_MASK, INTERP_MTHD, INTERP_PNTS,
               FCST_THRESH, OBS_THRESH, COV_THRESH, ALPHA, LINE_TYPE]

# Contains DESC but not UNITS
MID_HEADER = LONG_HEADER[0:10] + LONG_HEADER[11:13] + LONG_HEADER[14:]

# No DESC and no UNITS
SHORT_HEADER = MID_HEADER[0:2] + MID_HEADER[3:]

COL_NUMS = [str(x) for x in range(MAX_COL - 24)]
