name: METdataio CI/CD Workflow
on:
  push:
    branches:
      - develop
      - develop-ref
      - feature_*
      - main_*
      - bugfix_*
    paths-ignore:
      - 'docs/**'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '**/README.md'
      - '**/LICENSE.md'

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: python -m pip install --upgrade sphinx sphinx-gallery sphinx_rtd_theme
      - name: Build documentation
        continue-on-error: true
        run: ./.github/jobs/build_documentation.sh
      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: artifact/documentation
      - uses: actions/upload-artifact@v4
        with:
          name: documentation_warnings.log
          path: artifact/doc_warnings.log
          if-no-files-found: ignore
